version: '3.9'

services:
  backend:
     image: asterisk-backend1 
     networks:
      - app-network
    

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Lê a senha do root do .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}            # Lê o nome do banco de dados do .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"  # Porta mapeada para o navegador
    networks:
      - app-network
    environment:
      PMA_HOST: ${PMA_HOST}           # Nome do serviço MySQL no Docker Compose
      PMA_USER: ${PMA_USER}           # Usuário root do MySQL
      PMA_PASSWORD: ${PMA_PASSWORD}   # Senha do root (lê do .env)
    depends_on:
      - mysql  # phpMyAdmin depende do serviço mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
