# Etapa 1: Definir a imagem base do Node.js 19
FROM node:19-alpine

# Etapa 2: Definir o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Etapa 3: Copiar o package.json e package-lock.json (se existir)
COPY package*.json ./

# Etapa 4: Instalar as dependências do projeto
RUN npm install --frozen-lockfile

# Etapa 5: Copiar todos os arquivos do projeto para o diretório de trabalho no container
COPY . .

# Etapa 6: Compilar o código TypeScript (se necessário)
RUN npm run build

# Etapa 7: Expor a porta que o servidor Express vai rodar
EXPOSE 3000

# Etapa 8: Rodar o servidor Express
CMD ["npm", "start"]
